In [87]:
import numpy as np

A = np.random.randint(10, size = (5, 5))
print("A")
print(A)
print("W")

W, V = np.linalg.eig(A)
print(W)
print("V")
print(V)
print("Vinv")

Vinv = np.linalg.inv(V)
print(Vinv)
print("B")

B = np.dot(np.dot(V, np.diag(W)), Vinv)
print(B)
print("S")

S = min(W)

print(S)
print("C")

w = W.copy()

for i in range(len(W)):
    w[i] = W[i] - S + 0.1


C = np.dot(np.dot(V, np.diag(w)), Vinv)
print(C)
print("NewEW")

eW, eV = np.linalg.eig(C)
print(eW)
print("Diff")

Diff = A - C
print(Diff)

EW, EV = np.linalg.eig()

A
[[4 6 3 3 2]
 [6 2 7 2 2]
 [1 9 0 3 5]
 [7 9 6 9 4]
 [4 5 9 1 0]]
W
[ 21.16822886  -8.82060222  -2.80741224   1.26073135   4.19905425]
V
[[-0.3465952  -0.10548622 -0.20502321 -0.72468661 -0.07168852]
 [-0.34465607  0.43141252  0.4649892  -0.1781894   0.16459081]
 [-0.34401262 -0.71400262  0.09891975  0.43804618  0.2349434 ]
 [-0.73166459 -0.05686281  0.00667682  0.32658293 -0.85411639]
 [-0.32772885  0.53825902 -0.85552372  0.3801802   0.4278521 ]]
Vinv
[[-0.50992665 -0.68829315 -0.54874195 -0.40030964 -0.31846726]
 [-0.3786946   0.59330381 -0.74748107  0.10461535  0.32761091]
 [-0.42897918  0.87829163  0.1673507  -0.03405272 -0.56962333]
 [-0.96828657 -0.0585371   0.26242545  0.25868919  0.23259248]
 [ 0.0884409   0.53459902  0.62148435 -0.7361997   0.33548098]]
B
[[  4.00000000e+00   6.00000000e+00   3.00000000e+00   3.00000000e+00
    2.00000000e+00]
 [  6.00000000e+00   2.00000000e+00   7.00000000e+00   2.00000000e+00
    2.00000000e+00]
 [  1.00000000e+00   9.00000000e+00  -4.32